OVL:
  detection_fscore: 0.0
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.9918693812442166
    onset: 0.9918693812442166
    pad_offset: 0.0
    pad_onset: 0.0
SPEECH:
  detection_fscore: 0.8721636270222825
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.3577073665243799
    onset: 0.3577073665243799
    pad_offset: 0.0
    pad_onset: 0.0
average_detection_fscore: 0.3394284235161477
epoch: 20
fem:
  detection_fscore: 0.41119223781912606
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.2640599116417926
    onset: 0.2640599116417926
    pad_offset: 0.0
    pad_onset: 0.0
kchi:
  detection_fscore: 0.6517541854508351
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.3499861974085131
    onset: 0.3499861974085131
    pad_offset: 0.0
    pad_onset: 0.0
labels_spec:
  intersection:
    OVL:
    - kchi
    - och
    - fem
    - mal
    - ovh
    - unk
  regular:
  - kchi
  - och
  - fem
  - mal
  - ovh
  union:
    SPEECH:
    - kchi
    - och
    - fem
    - mal
    - ovh
    - unk
mal:
  detection_fscore: 0.44088891432079036
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.13178714348921966
    onset: 0.13178714348921966
    pad_offset: 0.0
    pad_onset: 0.0
och:
  detection_fscore: 0.0
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.9918693812442166
    onset: 0.9918693812442166
    pad_offset: 0.0
    pad_onset: 0.0
ovh:
  detection_fscore: 0.0
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.9918693812442166
    onset: 0.9918693812442166
    pad_offset: 0.0
    pad_onset: 0.0
