CDS:
  detection_fscore: 1.0
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.9918693812442166
    onset: 0.9918693812442166
    pad_offset: 0.0
    pad_onset: 0.0
KCHI:
  detection_fscore: 0.6812741712983231
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.2805131922728808
    onset: 0.2805131922728808
    pad_offset: 0.0
    pad_onset: 0.0
OHS:
  detection_fscore: 1.0
  params:
    min_duration_off: 0.1
    min_duration_on: 0.1
    offset: 0.9918693812442166
    onset: 0.9918693812442166
    pad_offset: 0.0
    pad_onset: 0.0
average_detection_fscore: 0.8937580570994411
epoch: 5
labels_spec:
  intersection: {}
  regular:
  - KCHI
  - CDS
  - OHS
  union: {}
